// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw0YKzpvsmQDjeV5QI4gkfLnqgb8GDHrs',
    appId: '1:633823231381:web:9e5b47f9e6b4aeb9f04a9c',
    messagingSenderId: '633823231381',
    projectId: 'tasklink-54de8',
    authDomain: 'tasklink-54de8.firebaseapp.com',
    storageBucket: 'tasklink-54de8.firebasestorage.app',
    measurementId: 'G-5N79S8D3KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnFzN4DEHSnEL1YkGbAL6LTrdW0E_vH4M',
    appId: '1:633823231381:android:9ba330061115d753f04a9c',
    messagingSenderId: '633823231381',
    projectId: 'tasklink-54de8',
    storageBucket: 'tasklink-54de8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAVSOhbzCdjbuZfSurPKdOb8o3Jj1xC1E',
    appId: '1:633823231381:ios:e3acd968456923d6f04a9c',
    messagingSenderId: '633823231381',
    projectId: 'tasklink-54de8',
    storageBucket: 'tasklink-54de8.firebasestorage.app',
    iosBundleId: 'com.example.errandApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAVSOhbzCdjbuZfSurPKdOb8o3Jj1xC1E',
    appId: '1:633823231381:ios:3d076db9d94c5a81f04a9c',
    messagingSenderId: '633823231381',
    projectId: 'tasklink-54de8',
    storageBucket: 'tasklink-54de8.firebasestorage.app',
    iosBundleId: 'com.david.errandApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw0YKzpvsmQDjeV5QI4gkfLnqgb8GDHrs',
    appId: '1:633823231381:web:79909d5645ed05eef04a9c',
    messagingSenderId: '633823231381',
    projectId: 'tasklink-54de8',
    authDomain: 'tasklink-54de8.firebaseapp.com',
    storageBucket: 'tasklink-54de8.firebasestorage.app',
    measurementId: 'G-L3N7LBKHQT',
  );
}
